name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master  # Trigger deploy on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up .NET SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'  # Use the version of .NET Core you are using (e.g., 3.1, 5.0, 6.0)

      # Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore ./src/Services/

      # Build the project
      - name: Build the project
        run: dotnet build ./src/Services/ --configuration Release

      # Run tests (optional)
      - name: Run tests
        run: dotnet test ./src/Services/ --configuration Release

      # Publish the project to a folder
      - name: Publish the project
        run: dotnet publish ./src/Services/ --configuration Release --output ./publish

      # Create zip package for Elastic Beanstalk deployment
      - name: Create zip for deployment
        run: |
          zip -r deploy-package.zip ./publish/*
