name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master  # Trigger deploy on push to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up .NET SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'  # Ensure this matches your .NET version

      # Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build the project
        run: dotnet build --configuration Release

      # Run tests (optional)
      - name: Run tests
        run: dotnet test --configuration Release

      # Publish the project to a folder
      - name: Publish the project
        run: dotnet publish --configuration Release --output ./publish

      # Create zip package for Elastic Beanstalk deployment
      - name: Create zip for deployment
        run: |
          zip -r deploy-package.zip ./publish/*

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures that the deploy step runs after the build step

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'  # Specify your AWS region here

      # Deploy to AWS Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        run: |
          # Install AWS EB CLI
          pip install awsebcli

          # Initialize Elastic Beanstalk application with the correct platform
          eb init bidwheels-api-version-1 --platform ".NET 8 running on 64bit Amazon Linux 2023/3.2.2" --region us-east-1  # Adjusted platform

          # Use the environment (ensure the environment exists)
          eb use Bidwheels-api-env  # Change to your actual Elastic Beanstalk environment name

          # Deploy the package
          eb deploy
