name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    - name: Install dependencies
      run: dotnet restore ./src/Services/

    - name: Build
      run: dotnet build -./src/Services/ -configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./src/Services/ --configuration Release --no-build --output ./publish

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
      run: |
        zip -r deploy.zip ./publish
        eb init -p ".NET 8 running on 64bit Amazon Linux 2023/3.2.2" --region $AWS_REGION --defaults
        eb use Bidwheels-api-env
        eb deploy --staged
