name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master  # Trigger deploy on push to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up .NET SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'  # Ensure this matches your .NET version

      # Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore ./src/Services/

      # Build the project
      - name: Build the project
        run: dotnet build ./src/Services/ --configuration Release

      # Run tests (optional)
      - name: Run tests
        run: dotnet test ./src/Services/ --configuration Release

      # Publish the project to a folder
      - name: Publish the project
        run: dotnet publish ./src/Services/ --configuration Release --output ./publish

      # Create zip package for Elastic Beanstalk deployment
      - name: Create zip for deployment
        run: |
          zip -r deploy-package.zip ./publish/*

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures that the deploy step runs after the build step

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'  # Specify your AWS region here

      # Deploy to AWS Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: actions/checkout@v3
 
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
        
      - name: Install AWS EB CLI
        run: pip install awsebcli
        
      - name: Initialize Elastic Beanstalk Application - I
        run: eb init bidwheels-api-version-2 --platform ".NET 8 running on 64bit Amazon Linux 2023/3.2.2" --region us-east-1
          
      - name: Use Elastic Beanstalk Environment
        run: eb use Bidwheels-api-env
 
      - name: Deploy to Elastic Beanstalk
        run: eb deploy
